"""Starlink gRPC wrapper for StarBoard.

Questo modulo wrappa la libreria starlink_grpc_tools per fornire
un'interfaccia compatibile con StarBoard.
"""

import logging
import time
from typing import Any, Optional

logger = logging.getLogger(__name__)

STARLINK_IP = "192.168.100.1"
STARLINK_PORT = 9200


def fetch_grpc_data() -> dict[str, Any]:
    """Recupera dati reali dall'antenna Starlink via gRPC.

    Returns:
        Dict contenente tutti i dati della dashboard Starlink.
    """
    try:
        # Import the working library
        from starlink_grpc_tools import status_data, GrpcError

        # Get real status data from Starlink antenna
        status, obstruction, alerts = status_data()

        logger.info(f"Got real data from Starlink: state={status.get('state')}")

        # Build the response dict matching StarBoard format
        result = {
            "status": "success",
            "online": True,
            "mode": "device",
            "grpc_real": True,  # Mark this as real gRPC data

            # Data source tracking (which fields are real vs simulated)
            "_source": {
                "hardware_version": "real",
                "software_version": "real",
                "uptime": "real",
                "ping": "real",
                "latency": "real",
                "packet_loss": "real",
                "download": "speedtest",  # From speedtest, not gRPC
                "upload": "speedtest",    # From speedtest, not gRPC
                "snr": "simulated",       # Generated by us
                "obstruction": "real",
                "currently_obstructed": "real",
                "azimuth": "real",
                "elevation": "real",
                "satellites": "real",
                "obstruction_events": "simulated",  # Not available
                "last_24h_obstructed_s": "simulated",  # Not available
            },

            # Basic info
            "id": status.get("id", ""),
            "hardware_version": status.get("hardware_version", ""),
            "software_version": status.get("software_version", ""),
            "state": status.get("state", "UNKNOWN"),

            # Uptime (convert seconds to readable format)
            "uptime": _format_uptime(status.get("uptime")),

            # Network stats
            "ping": round(status.get("pop_ping_latency_ms", 0) or 0, 1),
            "ping_unit": "ms",
            "latency": int(status.get("pop_ping_latency_ms", 0) or 0),
            "packet_loss": round((status.get("pop_ping_drop_rate", 0) or 0) * 100, 2),

            # Throughput (convert bps to Mbps)
            "download": round((status.get("downlink_throughput_bps", 0) or 0) / 1_000_000, 2),
            "upload": round((status.get("uplink_throughput_bps", 0) or 0) / 1_000_000, 2),
            "speed_unit": "Mbps",

            # Signal/Obstruction data
            "snr": _generate_snr(status.get("gps_sats", 0) or 0, status.get("fraction_obstructed", 0) or 0),  # Generated realisti
            "obstruction": round((status.get("fraction_obstructed", 0) or 0) * 100, 2),
            "currently_obstructed": bool(status.get("currently_obstructed", False)),

            # Directional data
            "azimuth": round(status.get("direction_azimuth", 0) or 0, 1),
            "elevation": round(status.get("direction_elevation", 0) or 0, 1),

            # GPS/Satellite data
            "satellites": status.get("gps_sats", 0) or 0,

            # Alert bits (for debugging)
            "alerts": status.get("alerts", 0),
        }

        # Add obstruction details
        if obstruction:
            result["obstruction_events"] = 0  # Not available in current API
            result["last_24h_obstructed_s"] = 0  # Not available in current API
            result["last_obstruction_time"] = None

        # Add individual alert flags
        for key, value in alerts.items():
            result[key] = value

        return result

    except ImportError as e:
        logger.error(f"Failed to import starlink_grpc_tools: {e}")
        return None

    except Exception as e:
        logger.error(f"Failed to fetch gRPC data: {e}")
        return None


def _generate_snr(satellites: int, obstruction: float) -> float:
    """Generate a realistic SNR value based on satellites and obstruction.

    Args:
        satellites: Number of GPS satellites
        obstruction: Fraction of obstruction (0-1)

    Returns:
        Realistic SNR value in dB
    """
    import random

    # Base SNR between 8-10
    base_snr = 8 + random.random() * 2

    # Add bonus for more satellites (above 10)
    if satellites > 10:
        base_snr += (satellites - 10) * 0.2

    # Reduce for obstruction
    base_snr -= obstruction * 3

    # Clamp between 4 and 12
    return round(max(4, min(12, base_snr)), 1)


def _format_uptime(uptime_seconds: Optional[int]) -> str:
    """Format uptime seconds to readable string.

    Args:
        uptime_seconds: Uptime in seconds

    Returns:
        Formatted uptime string (e.g., "2d 14h 32m")
    """
    if not uptime_seconds:
        return "--"

    days = uptime_seconds // 86400
    hours = (uptime_seconds % 86400) // 3600
    minutes = (uptime_seconds % 3600) // 60

    if days > 0:
        return f"{days}d {hours}h {minutes}m"
    elif hours > 0:
        return f"{hours}h {minutes}m"
    else:
        return f"{minutes}m"


def test_connection() -> dict[str, Any]:
    """Testa la connessione con l'antenna Starlink.

    Returns:
        Dict con risultato del test
    """
    try:
        from starlink_grpc_tools import get_id

        device_id = get_id()
        return {
            "success": True,
            "device_id": device_id,
            "message": "Successfully connected to Starlink antenna"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "message": "Failed to connect to Starlink antenna"
        }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    print("Testing Starlink gRPC connection...")
    print("=" * 50)

    test = test_connection()
    print(f"\nConnection test: {test['success']}")
    if test.get('success'):
        print(f"Device ID: {test.get('device_id')}")

    print("\n" + "=" * 50)
    print("Fetching data from Starlink...")
    print("=" * 50)

    data = fetch_grpc_data()

    if data:
        print("\nSuccessfully retrieved real data!")
        print(f"  State: {data.get('state')}")
        print(f"  Hardware: {data.get('hardware_version')}")
        print(f"  Software: {data.get('software_version')}")
        print(f"  Uptime: {data.get('uptime')}")
        print(f"  Ping: {data.get('ping')} ms")
        print(f"  Download: {data.get('download')} Mbps")
        print(f"  Upload: {data.get('upload')} Mbps")
        print(f"  Azimuth: {data.get('azimuth')}°")
        print(f"  Elevation: {data.get('elevation')}°")
        print(f"  Satellites: {data.get('satellites')}")
        print(f"  Obstruction: {data.get('obstruction')}%")
        print(f"  Currently obstructed: {data.get('currently_obstructed')}")
    else:
        print("\nFailed to retrieve data")
